### ISSUE TITLE
recorded data not working

### ISSUE THREAD

**Issue by xuguozhi** [think-biq/LLV#1]
Hi, thanks for your amazing tools!
I followed the youtube tutorial for playing default data by the following command, and it works fine in UE4 Metahuman
```
python llv.py play .\examples\dao.gesichter
```
However, when I am recording my own facial motion using this command
```
python llv.py record --port 11011 --output shuzhi.gesichter
```
the data can be generated successfully
But problems come when playing my own shuzhi.gesichter file:
```
 python llv.py play .\examples\shuzhi.gesichter
```
UE metahuman just don't move
```
PS D:\shuzhi\metahuman\LLV> python llv.py play .\examples\shuzhi.gesichter
Establish connection ({'remote': ('localhost', 11111), 'local': ('127.0.0.1', 57251)}) ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
Start sending 180 frames of version 6 @60fps ...
```

**Comment by xuguozhi** [comment]
Oh~ I find the solutions!:
in the UE LLink Face Subj choose your iPhone device not "LLV Default Device", then the recorded data should work :)

**Comment by BlurryRoots** [comment]
Hey @xuguozhi, thanks for clearing up the solution for the issue you described. If you want the subject name to be different, you might want to consider using the command unpack to unpack a raw recording, and then pack it again using a custom device name via the --rename option.
