### ISSUE TITLE
realtime reciving and playing

### ISSUE THREAD

**Issue by xuguozhi** [think-biq/LLV#2]
Hi, I want to do small modifications to the BS data, such as filtering, if it is possible to get iPhone arkit data and then play the data to UE simultaneously?
---------UPDATE--------
Maybe start two different sockets (server/client) will be helpful.

**Comment by xuguozhi** [comment]
Cause I want to do small modifications to the BS data

**Comment by BlurryRoots** [comment]
Hi @xuguozhi, thanks for reaching out. Please formulate your question in a more coherent way. If you put no effort in asking a question, why would you expect a quality answer. My suggestion: Delete your second comment, and edit the first one to include a description of the usage scenarion and the result you are looking for. Checkout [this gist](https://gist.github.com/auremoser/72803ba969d0e61ff070) for inspiration on how to structure an issue.

**Comment by xuguozhi** [comment]
I have solved this issue. thx.

**Comment by BlurryRoots** [comment]
> I have solved this issue. thx.

Hi @xuguozhi, glad to hear. Would you like share a bit more detail on how you approached this? Might help other people who are looking to archive similar results (and I am also curious)  ;)

**Comment by xuguozhi** [comment]
@BlurryRoots The background scenario is filtering the jitter and random shake of head pose(yaw pitch row). 

- So I apply the pc as the post process server. 
-  I start two buchse (bushesIn & buchseOut). 
- In Livelink Face app deleted the default port 11111, just remain one like 11011, iPhone data only transmitted to the llv server not to UE.
- In LLV I added OneEuro Filter on the selected blendshape curve, and get the filterd BS data.
- Using buchseOut to push the filterd data to UE.
- above code is based on ```def playback()```
